spring.application.name=PadelApp

spring.datasource.url=jdbc:mysql://localhost:3306/padelapp
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8